type = "webpack"
zone_id = ""
account_id = ""
workers_dev = true
webpack_config = "webpack.config.js"
name = "cfworker-poc-local"
vars = { ENVIRONMENT = "local" }

[env.dev]
route = "dev-api.vivek-rajagopal.net/*"
name = "cfworker-poc-dev"
vars = { ENVIRONMENT = "dev" }

[env.production]
route = "api.vivek-rajagopal.net/*"
name = "cfworker-poc"
vars = { ENVIRONMENT = "production" }